// Constantes para tipos de imóvel, características, etc.

export const PROPERTY_TYPES = [
  // Residencial
  { value: 'apartamento', label: 'Apartamento', category: 'Residencial' },
  { value: 'casa_rua', label: 'Casa de Rua', category: 'Residencial' },
  { value: 'casa_condominio', label: 'Casa em Condomínio', category: 'Residencial' },
  { value: 'studio_kitnet', label: 'Studio / Kitnet', category: 'Residencial' },
  { value: 'cobertura', label: 'Cobertura', category: 'Residencial' },
  { value: 'flat', label: 'Flat', category: 'Residencial' },
  { value: 'terreno_rua', label: 'Terreno de Rua', category: 'Residencial' },
  { value: 'terreno_condominio', label: 'Terreno em Condomínio', category: 'Residencial' },
  
  // Comercial
  { value: 'sala_comercial', label: 'Sala Comercial', category: 'Comercial' },
  { value: 'ponto_loja', label: 'Ponto/Loja', category: 'Comercial' },
  { value: 'galpao', label: 'Galpão/Depósito/Barracão', category: 'Comercial' },
  { value: 'consultorio', label: 'Consultório', category: 'Comercial' },
  
  // Rural
  { value: 'sitio_fazenda', label: 'Sítio/Fazenda', category: 'Rural' },
  { value: 'chacara_rancho', label: 'Chácara/Rancho', category: 'Rural' },
  { value: 'gleba', label: 'Gleba', category: 'Rural' },
];

export const PROPERTY_CATEGORIES = ['Residencial', 'Comercial', 'Rural'];

export const PROPERTY_FEATURES = [
  'Ar Condicionado',
  'Armários na Cozinha',
  'Armários Embutidos',
  'Varanda',
  'Área de Serviço',
  'Dependência de Empregados',
  'Lareira',
  'Jacuzzi',
  'Automação Residencial',
  'Sistema de Alarme',
  'Aquecedor Solar de Água',
  'Mobiliado',
  'Home office / Escritório',
  'Internet / Wi Fi',
  'Depósito',
  'Despensa',
  'Pé-direito alto',
  'Gerador de Energia solar',
  'Tomada para carro elétrico',
];

export const CONDO_AMENITIES = [
  'Piscina',
  'Churrasqueira',
  'Salão de Festas',
  'Espaço Gourmet',
  'Quadra Esportiva',
  'Portaria 24h',
  'Sauna',
  'Jardim',
  'Acesso para Deficientes',
  'Coworking',
  'Mercado no Condomínio',
  'Carregador Veicular',
  'Serviço de concierge / administração',
  'Bicicletário',
  'Sistema de coleta seletiva / sustentabilidade',
  'Cinema',
  'Salão de convenções / business center',
  'Academia',
  'Playground',
  'Elevador',
  'Aceita Animais',
  'Geração Solar de Energia',
  'Espaço Pet',
  'Estacionamento para visitantes',
  'Salão de jogos',
];

export const NEARBY_AMENITIES = [
  'Hospital',
  'Pronto Socorro',
  'Posto de Saúde',
  'Farmácia',
  'Padaria',
  'Quitanda',
  'Varejão',
  'Açougues',
  'Restaurante',
  'Supermercado',
  'Hipermercado',
  'Academia',
  'Praça Pública',
  'Parques',
  'Bosques',
  'Áreas Verdes',
  'Clubes',
  'Rodovias',
  'Estradas',
  'Clínicas',
  'Centros Comerciais',
  'Shoppings',
  'Rios',
  'Riachos',
  'Lagos/Lagoas',
  'Monumentos',
  'Pontos Turísticos',
  'Igrejas',
  'Templos',
  'Colégios/Escolas',
  'Universidades',
  'Distrito Industrial',
  'Centros Esportivos',
];

export const MARITAL_STATUS_OPTIONS = [
  { value: 'solteiro', label: 'Solteiro(a)' },
  { value: 'casado', label: 'Casado(a)' },
  { value: 'uniao_estavel', label: 'União Estável' },
  { value: 'divorciado', label: 'Divorciado(a)' },
  { value: 'viuvo', label: 'Viúvo(a)' },
];

export const DOCUMENT_TYPES = [
  'IPTU',
  'Matrícula do Imóvel',
  'Certidão Negativa de Débitos Municipais',
  'Certidão Negativa de Débitos Estaduais',
  'Certidão Negativa de Débitos Federais',
  'Certidão Negativa de Débitos Trabalhistas',
  'Comprovante de Renda',
  'Contrato de Locação',
  'Escritura',
  'RG Proprietário',
  'CPF Proprietário',
  'Comprovante de Residência',
  'Confissão de Dívida',
  'Termo de Vistoria',
  'Outros',
];
