-- This script was generated by the Supabase CLI.
-- You can remove this file if not planning to use it.

CREATE TABLE public.company_public_pages (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    company_id uuid REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    template_content TEXT,
    is_published BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
);

-- Optional: Add indexes for foreign keys and frequently queried columns
CREATE INDEX idx_company_public_pages_company_id ON public.company_public_pages (company_id);
CREATE INDEX idx_company_public_pages_slug ON public.company_public_pages (slug);

-- Habilita RLS
ALTER TABLE public.company_public_pages ENABLE ROW LEVEL SECURITY;

-- Policies de Segurança
CREATE POLICY "Public pages are viewable by everyone."
  ON public.company_public_pages FOR SELECT
  USING (true);

CREATE POLICY "Companies can create their own public pages." ON public.company_public_pages
  FOR INSERT WITH CHECK (auth.uid() IN ( SELECT id FROM public.profiles WHERE company_id = company_public_pages.company_id AND user_type = 'admin' ));

CREATE POLICY "Companies can update their own public pages." ON public.company_public_pages
  FOR UPDATE USING (auth.uid() IN ( SELECT id FROM public.profiles WHERE company_id = company_public_pages.company_id AND user_type = 'admin' ));

CREATE POLICY "Companies can delete their own public pages." ON public.company_public_pages
  FOR DELETE USING (auth.uid() IN ( SELECT id FROM public.profiles WHERE company_id = company_public_pages.company_id AND user_type = 'admin' ));
