-- This script was generated by the Supabase CLI.
-- You can remove this file if not planning to use it.

CREATE TABLE public.public_contact_requests (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    company_id uuid REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,
    property_id uuid REFERENCES public.properties(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    message TEXT,
    responded_at TIMESTAMP WITH TIME ZONE,
    responded_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
);

-- Optional: Add indexes for foreign keys and frequently queried columns
CREATE INDEX idx_public_contact_requests_company_id ON public.public_contact_requests (company_id);
CREATE INDEX idx_public_contact_requests_property_id ON public.public_contact_requests (property_id);
CREATE INDEX idx_public_contact_requests_responded_by ON public.public_contact_requests (responded_by);

-- Optional: Add RLS policies (TODOS os usuários da empresa podem ver/editar, não apenas admins)
ALTER TABLE public.public_contact_requests ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Company users can view their company contact requests." ON public.public_contact_requests
  FOR SELECT USING (auth.uid() IN ( SELECT id FROM public.profiles WHERE company_id = public_contact_requests.company_id ));

CREATE POLICY "Anyone can insert a contact request." ON public.public_contact_requests
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Company users can update their company contact requests." ON public.public_contact_requests
  FOR UPDATE USING (auth.uid() IN ( SELECT id FROM public.profiles WHERE company_id = public_contact_requests.company_id ));

CREATE POLICY "Company users can delete their company contact requests." ON public.public_contact_requests
  FOR DELETE USING (auth.uid() IN ( SELECT id FROM public.profiles WHERE company_id = public_contact_requests.company_id ));
