-- This script was generated by the Supabase CLI.
-- You can remove this file if not planning to use it.

ALTER TABLE public.properties
ADD COLUMN is_featured BOOLEAN DEFAULT FALSE NOT NULL;

-- Add a unique partial index to ensure only one featured property per company
CREATE UNIQUE INDEX ON public.properties (company_id) WHERE is_featured = TRUE;
